<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit96e10bad5a73581c8a274eeb8b46f91d
{
    public static $prefixLengthsPsr4 = array (
        'A' => 
        array (
            'Ateso_Dictionary\\' => 17,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Ateso_Dictionary\\' => 
        array (
            0 => __DIR__ . '/../..' . '/core',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit96e10bad5a73581c8a274eeb8b46f91d::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit96e10bad5a73581c8a274eeb8b46f91d::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit96e10bad5a73581c8a274eeb8b46f91d::$classMap;

        }, null, ClassLoader::class);
    }
}
