<?php

namespace ATESO_ENG\Admin;

use ATESO_ENG\Base\BaseController;
use ATESO_ENG\Database\Schema;
use ATESO_ENG\Database\TermRepository;
use ATESO_ENG\Database\DefinitionRepository;
use ATESO_ENG\Database\ExampleRepository;
use ATESO_ENG\Database\RelationRepository;

class ImportPage extends BaseController {

	public function register() {
		add_action( 'wp_ajax_ateso_dict_import_chunk', array( $this, 'handle_import_chunk' ) );
		add_action( 'wp_ajax_ateso_dict_resolve_relations', array( $this, 'handle_resolve_relations' ) );
	}

	public function render() {
		$term_repo  = new TermRepository();
		$term_count = $term_repo->get_total_count();
		?>
		<div class="wrap">
			<h1>Import Dictionary Data</h1>

			<?php if ( $term_count > 0 ) : ?>
				<div class="notice notice-info">
					<p>The dictionary currently contains <strong><?php echo esc_html( number_format( $term_count ) ); ?></strong> entries.
					Importing will replace all existing data.</p>
				</div>
			<?php endif; ?>

			<div id="ateso-import-upload" class="card" style="max-width: 800px;">
				<h2>Upload JSON File</h2>
				<p>Upload the JSON file generated by <code>tools/convert_dictionary.py</code>.</p>

				<input type="file" id="ateso-import-file" accept=".json" />
				<p class="description">Maximum upload size: <?php echo esc_html( size_format( wp_max_upload_size() ) ); ?></p>
			</div>

			<div id="ateso-import-preview" class="card" style="max-width: 800px; display: none;">
				<h2>Import Preview</h2>
				<div id="ateso-import-stats"></div>
				<p>
					<button type="button" id="ateso-import-start" class="button button-primary">Start Import</button>
					<button type="button" id="ateso-import-cancel" class="button">Cancel</button>
				</p>
			</div>

			<div id="ateso-import-progress" class="card" style="max-width: 800px; display: none;">
				<h2>Importing...</h2>
				<div style="background: #f0f0f0; border-radius: 4px; overflow: hidden; margin: 16px 0;">
					<div id="ateso-import-bar" style="background: #0073aa; height: 24px; width: 0%; transition: width 0.3s; border-radius: 4px;"></div>
				</div>
				<p id="ateso-import-status">Preparing import...</p>
			</div>

			<div id="ateso-import-result" class="card" style="max-width: 800px; display: none;">
				<h2>Import Complete</h2>
				<div id="ateso-import-result-content"></div>
			</div>
		</div>

		<script>
		(function() {
			const fileInput = document.getElementById('ateso-import-file');
			const uploadSection = document.getElementById('ateso-import-upload');
			const previewSection = document.getElementById('ateso-import-preview');
			const progressSection = document.getElementById('ateso-import-progress');
			const resultSection = document.getElementById('ateso-import-result');
			const statsDiv = document.getElementById('ateso-import-stats');
			const startBtn = document.getElementById('ateso-import-start');
			const cancelBtn = document.getElementById('ateso-import-cancel');
			const progressBar = document.getElementById('ateso-import-bar');
			const statusText = document.getElementById('ateso-import-status');
			const resultContent = document.getElementById('ateso-import-result-content');

			let jsonData = null;
			const CHUNK_SIZE = 100;

			fileInput.addEventListener('change', function(e) {
				const file = e.target.files[0];
				if (!file) return;

				const reader = new FileReader();
				reader.onload = function(evt) {
					try {
						jsonData = JSON.parse(evt.target.result);

						if (!jsonData.entries || !Array.isArray(jsonData.entries)) {
							alert('Invalid JSON format: missing "entries" array.');
							return;
						}

						const stats = jsonData.metadata?.stats || {};
						let html = '<table class="widefat striped"><tbody>';
						html += '<tr><th>Total entries</th><td>' + jsonData.entries.length + '</td></tr>';
						if (stats.total_definitions) html += '<tr><th>Total definitions</th><td>' + stats.total_definitions + '</td></tr>';
						if (stats.total_examples) html += '<tr><th>Total examples</th><td>' + stats.total_examples + '</td></tr>';
						if (stats.by_pos) {
							html += '<tr><th>By POS</th><td>';
							for (const [pos, count] of Object.entries(stats.by_pos)) {
								html += (pos || '(none)') + ': ' + count + '<br>';
							}
							html += '</td></tr>';
						}
						if (stats.by_letter) {
							html += '<tr><th>By letter</th><td>';
							for (const [letter, count] of Object.entries(stats.by_letter)) {
								html += letter + ': ' + count + '&nbsp;&nbsp;';
							}
							html += '</td></tr>';
						}
						html += '</tbody></table>';
						statsDiv.innerHTML = html;

						uploadSection.style.display = 'none';
						previewSection.style.display = '';
					} catch (err) {
						alert('Error parsing JSON: ' + err.message);
					}
				};
				reader.readAsText(file);
			});

			cancelBtn.addEventListener('click', function() {
				jsonData = null;
				fileInput.value = '';
				previewSection.style.display = 'none';
				uploadSection.style.display = '';
			});

			startBtn.addEventListener('click', async function() {
				if (!jsonData) return;

				previewSection.style.display = 'none';
				progressSection.style.display = '';

				const entries = jsonData.entries;
				const totalChunks = Math.ceil(entries.length / CHUNK_SIZE);
				let imported = 0;
				let errors = 0;

				// First: truncate existing data.
				statusText.textContent = 'Clearing existing data...';
				try {
					const truncRes = await doAjax('ateso_dict_import_chunk', {
						action_type: 'truncate'
					});
					if (!truncRes.success) {
						statusText.textContent = 'Error clearing data: ' + (truncRes.data?.message || 'Unknown');
						return;
					}
				} catch (err) {
					statusText.textContent = 'Error clearing data: ' + err.message;
					return;
				}

				// Import chunks.
				for (let i = 0; i < totalChunks; i++) {
					const chunk = entries.slice(i * CHUNK_SIZE, (i + 1) * CHUNK_SIZE);
					const pct = Math.round(((i + 1) / totalChunks) * 100);
					progressBar.style.width = pct + '%';
					statusText.textContent = 'Importing entries ' + (i * CHUNK_SIZE + 1) + ' to ' + Math.min((i + 1) * CHUNK_SIZE, entries.length) + ' of ' + entries.length + '...';

					try {
						const res = await doAjax('ateso_dict_import_chunk', {
							action_type: 'import',
							entries: JSON.stringify(chunk)
						});
						if (res.success) {
							imported += res.data.imported || 0;
							errors += res.data.errors || 0;
						} else {
							errors += chunk.length;
						}
					} catch (err) {
						errors += chunk.length;
					}
				}

				// Resolve relations.
				statusText.textContent = 'Resolving cross-references...';
				progressBar.style.width = '100%';

				try {
					await doAjax('ateso_dict_resolve_relations', {});
				} catch (err) {
					// Non-fatal.
				}

				// Show result.
				progressSection.style.display = 'none';
				resultSection.style.display = '';

				let html = '<div class="notice notice-success inline"><p>';
				html += 'Successfully imported <strong>' + imported + '</strong> entries.';
				if (errors > 0) {
					html += ' <span style="color: #d63638;">' + errors + ' errors.</span>';
				}
				html += '</p></div>';
				html += '<p><a href="' + encodeURI('<?php echo esc_url( admin_url( 'admin.php?page=ateso-dictionary' ) ); ?>') + '" class="button">View All Entries</a></p>';
				resultContent.innerHTML = html;
			});

			function doAjax(action, data) {
				const formData = new FormData();
				formData.append('action', action);
				formData.append('_wpnonce', '<?php echo esc_js( wp_create_nonce( 'ateso_dict_import' ) ); ?>');
				for (const [key, val] of Object.entries(data)) {
					formData.append(key, val);
				}

				return fetch('<?php echo esc_url( admin_url( 'admin-ajax.php' ) ); ?>', {
					method: 'POST',
					body: formData,
					credentials: 'same-origin'
				}).then(r => r.json());
			}
		})();
		</script>
		<?php
	}

	/**
	 * Handle AJAX import chunk.
	 */
	public function handle_import_chunk() {
		check_ajax_referer( 'ateso_dict_import', '_wpnonce' );

		if ( ! current_user_can( 'manage_options' ) ) {
			wp_send_json_error( array( 'message' => 'Unauthorized' ) );
		}

		$action_type = sanitize_text_field( $_POST['action_type'] ?? '' );

		if ( 'truncate' === $action_type ) {
			Schema::truncate_tables();
			wp_send_json_success( array( 'message' => 'Tables truncated' ) );
		}

		if ( 'import' !== $action_type ) {
			wp_send_json_error( array( 'message' => 'Invalid action type' ) );
		}

		$raw_entries = json_decode( stripslashes( $_POST['entries'] ?? '[]' ), true );

		if ( ! is_array( $raw_entries ) ) {
			wp_send_json_error( array( 'message' => 'Invalid entries data' ) );
		}

		$term_repo = new TermRepository();
		$def_repo  = new DefinitionRepository();
		$ex_repo   = new ExampleRepository();
		$rel_repo  = new RelationRepository();

		$imported = 0;
		$errors   = 0;

		foreach ( $raw_entries as $entry ) {
			try {
				// Insert the term.
				$term_id = $term_repo->insert( array(
					'word'           => sanitize_text_field( $entry['word'] ?? '' ),
					'slug'           => sanitize_title( $entry['slug'] ?? $entry['word'] ?? '' ),
					'homonym_number' => isset( $entry['homonym_number'] ) ? absint( $entry['homonym_number'] ) : null,
					'plural'         => sanitize_text_field( $entry['plural'] ?? '' ) ?: null,
					'pos'            => sanitize_text_field( $entry['pos'] ?? '' ),
					'pos_detail'     => sanitize_text_field( $entry['pos_detail'] ?? '' ) ?: null,
					'gender'         => sanitize_text_field( $entry['gender'] ?? '' ) ?: null,
					'dialect'        => sanitize_text_field( $entry['dialect'] ?? '' ) ?: null,
					'verb_stem'      => sanitize_text_field( $entry['verb_stem'] ?? '' ) ?: null,
					'letter'         => sanitize_text_field( $entry['letter'] ?? '' ),
					'usage_labels'   => is_array( $entry['usage_labels'] ?? null )
						? sanitize_text_field( implode( ', ', $entry['usage_labels'] ) )
						: null,
					'sort_order'     => 0,
				) );

				if ( ! $term_id ) {
					++$errors;
					continue;
				}

				// Insert definitions.
				$definitions = $entry['definitions'] ?? array();
				$def_rows    = array();
				$rel_rows    = array();

				foreach ( $definitions as $i => $def ) {
					$def_rows[] = array(
						'term_id'         => $term_id,
						'definition_text' => sanitize_text_field( $def['text'] ?? '' ),
						'sort_order'      => $i,
					);

					// Collect cross-references from definitions.
					foreach ( $def['cp_refs'] ?? array() as $ref ) {
						$ref = sanitize_text_field( $ref );
						if ( $ref ) {
							$rel_rows[] = array(
								'term_id'       => $term_id,
								'related_word'  => $ref,
								'relation_type' => 'cp',
							);
						}
					}
				}

				if ( ! empty( $def_rows ) ) {
					$def_repo->bulk_insert( $def_rows );
				}

				// Insert examples.
				$examples = $entry['examples'] ?? array();
				$ex_rows  = array();

				foreach ( $examples as $i => $ex ) {
					$ex_rows[] = array(
						'term_id'      => $term_id,
						'ateso_text'   => sanitize_text_field( $ex['ateso'] ?? '' ),
						'english_text' => sanitize_text_field( $ex['english'] ?? '' ),
						'sort_order'   => $i,
					);
				}

				if ( ! empty( $ex_rows ) ) {
					$ex_repo->bulk_insert( $ex_rows );
				}

				// Insert relations.
				if ( ! empty( $rel_rows ) ) {
					$rel_repo->bulk_insert( $rel_rows );
				}

				++$imported;

			} catch ( \Exception $e ) {
				++$errors;
			}
		}

		wp_send_json_success( array(
			'imported' => $imported,
			'errors'   => $errors,
		) );
	}

	/**
	 * Handle relation resolution after import.
	 */
	public function handle_resolve_relations() {
		check_ajax_referer( 'ateso_dict_import', '_wpnonce' );

		if ( ! current_user_can( 'manage_options' ) ) {
			wp_send_json_error( array( 'message' => 'Unauthorized' ) );
		}

		$rel_repo = new RelationRepository();
		$resolved = $rel_repo->resolve_relations();

		wp_send_json_success( array( 'resolved' => $resolved ) );
	}
}
